# Generated by Django 3.1.2 on 2020-11-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='Record',
        ),
    ]
